### ISSUE TITLE
Random ENV failures when vars depend on each other

### ISSUE THREAD

**Issue by VojtechVitek** [pressly/sup#10]
Since YAML parses ENV vars into a map, we loose the declaration order, and thus the following randomly fails:

```yaml
env:
  WORKDIR: /var/www/
  CONFDIR: $WORKDIR/config # this becomes /var/www/config OR /config randomly
```
