### ISSUE TITLE
Do sequential commands run in different sessions?

### ISSUE THREAD

**Issue by basharov** [pressly/sup#106]
I am trying out sup and here is my Supfile

```
networks:
    staging:
      hosts:
        - root@myhost

commands:
    lsroot:
      desc: list root
      run: cd /; ls
    goroot:
      desc: go to root path
      run: cd /
    ls:
      desc: list files
      run: ls
```

When I run `sup staging lsroot`, it goes to root path / then lists the tree correctly.
But when I run `sup staging goroot ls`, it seems like two commands run in their own sessions, because `ls` shows content of /root folder, not /.

Is it an intentional behavior?
I'd like to run a list of commands in one session., like in `lsroot` example above.
