### ISSUE TITLE
per host env vars

### ISSUE THREAD

**Issue by untoreh** [pressly/sup#111]
what about something like this:
```yaml
networks:
 net:
   hosts:
   - endpoint: 192.168.121.2
     env:
       VAR: 1
```
