### ISSUE TITLE
Sudo won't accept password on remote host

### ISSUE THREAD

**Issue by jzs** [pressly/sup#112]
I have a command in my Supfile `sudo systemctl restart myservice.service`.

When running it against a localhost host it asks for a sudo password just fine, and accepts my input. However when running it against a remote ubuntu host, it doesn't show the password prompt and it looks like sup is hanging.
When pressing ^C then it prints: [sudo] password for xxxx: followed by terminating the connection.

Adding: `stdin:true` seems to do the trick, however it then prints out `[sudo] password for xxxx:` after i type my password. (It looks like it hangs, i write the password, it prints out [sudo] password for xxxx and then accepts the password i typed in. On the same time, my password is printed to the console when typeing. Hence no `read -s` functionality.

Alternatively adding `%xxxx ALL=NOPASSWD: /bin/systemctl stop myservice.service` to the sudoers file on the remote host also works. Since it will then skip asking for password.

Here's a minimal Supfile to recreate my issue:

```
# Supfile for myservice
---
version: 0.4

networks:
  dev:
    hosts:
      - localhost
  release:
    hosts:
      - myserver.com:999

commands:
  stop: 
    desc: Stop service
    run: sudo systemctl stop myservice.service
```

My Dev machine is running arch linux and the server is running Ubuntu 16.04.2 LTS.
