### ISSUE TITLE
Upload issues

### ISSUE THREAD

**Issue by slavaGanzin** [pressly/sup#114]
Hello thanks for your awesome project.

I had an issues with upload:

1. if ```src``` is not present I had no errors
1. ```-debug``` key didn't change this behaviour
1. there should be a message that something was(or not) copied
1. currently I see only tar (not so usefull) messages: ```tar: .config/fish/fundle/edc/bass/.git: time stamp 2017-06-20 15:47:40 is 199.705320196 s in the future ```
1. upload doesn't resolve local home dir using tilde ```~``` (As I found ```$HOME``` works, but...)
1. Relative path issue
```yaml
    upload:
      - src: ../.config/fish
        dst: /tmp

#will copy into /tmp/.config/fish
#but:
cp -r ../.config/fish /tmp
#will copy contents into /tmp/fish which is default behavior for unix
```

*****
```sh
sup -v                                                                  
# 0.5
uname -a
# Linux war 4.11.5-1-ARCH #1 SMP PREEMPT Wed Jun 14 16:19:27 CEST 2017 x86_64 GNU/Linux
go version
# go1.8.3 linux/amd64
```

Thanks
