### ISSUE TITLE
piping doesn't work with dropbear server

### ISSUE THREAD

**Issue by untoreh** [pressly/sup#141]
I have tested piping a bash script, trying to pipe to a dropbear ssh server returns
```
Process exited with status 129 from signal HUP
```
While quickly testing with sshd it works as intended.
Testing with with just the ssh client (standard openssh client)
```
echo "echo hello" | ssh user@dropbearhost bash
```
works so I don't know what golang ssh or sup does differently

**Comment by VojtechVitek** [comment]
Please, provide a full reproducer

**Comment by untoreh** [comment]
```yaml
# Supfile
version: 0.4

networks:
  test:
    hosts:
      - root@localhost:2222


commands:
  bash:
    desc: Interactive Bash on all hosts
    stdin: true
    run: >
      bash -l
targets:
```
dropbear
```bash
docker run --rm -it --net=host alpine sh -c "apk add --no-cache dropbear; mkdir -p /etc/dropbear; mkdir ~/.ssh; chmod 700 ~/.ssh; echo $SSH_KEY > ~/.ssh/authorized_keys; dropbear -p 2222 -REF"
```
sup
```bash
echo "hello" | sup test bash
```
