### ISSUE TITLE
SUP_ENV needs escaping

### ISSUE THREAD

**Issue by untoreh** [pressly/sup#154]
SUP_ENV is not escaped:
```
sup -D -e HELLO="1 2 3" local env
fra@localhost | bash: line 0: export: `2': not a valid identifier
fra@localhost | bash: line 0: export: `3': not a valid identifier
fra@localhost | + echo SUP_ENV is '-e HELLO=1'
fra@localhost | SUP_ENV is -e HELLO=1
```
```
commands:
  env:
    desc: print env
    run: echo SUP_ENV is "$SUP_ENV"

```
this one does not break but the quoting is lost
```
sup -D -e HELLO="'""1 2 3""'" local env
```
this one does not break and preserves quoting
```
sup -D -e HELLO='"'"'1 2 3'"'"' local env
```

**Comment by VojtechVitek** [comment]
Sup sets the env var as a string value, it shouldn't need any additional escaping.

I think you need to escape the "$HELLO" variable in the remote shell.

```
$ export HELLO="1 2 3"

$ $HELLO
bash: 1: command not found

$ "$HELLO"
bash: 1 2 3: command not found
```

Please, feel free to reopen if this doesn't help.

**Comment by untoreh** [comment]
I don't think I understood what you meant.
The point is that sup doesn't escape quotes in the SUP_ENV variable. And since sup (well the go ssh packagei guess) executes the command as an argument (`bash -c "export SUP...."`) it ends up like
 `bash -c "...; export SUP_ENV="HELLO=" 1 2 3" OTHER_VAR=X"; ... "` 
when it should be
 `bash -c "...; export SUP_ENV="HELLO=\" 1 2 3\" OTHER_VAR=X"; ... "` 
The user has no control over the SUP_ENV variable

**Comment by VojtechVitek** [comment]
I might have misunderstood then. Can you provide a reproducer Supfile?

**Comment by untoreh** [comment]
well there was already the command snippet just add a local network
```
# Supfile
version: 0.4
networks:
  local:
    hosts:
      - localhost
commands:
  env:
    desc: print env
    run: echo SUP_ENV is "$SUP_ENV"
```
