### ISSUE TITLE
Deploy multiples Sups

### ISSUE THREAD

**Issue by eduardonunesp** [pressly/sup#18]
Would be cool if `sup` have an option to work with "sub sups", so you can organize multiple deploys with only one command, for instance:

```
.
├── Supfile
├── project1
│   ├── Dockerfile
│   ├── Supfile
│   ├── example.dev.cfg
│   ├── example.go
│   ├── example.local.cfg
│   ├── example.prod.cfg
│   ├── example.stg.cfg
│   └── scripts
├── project2
│   ├── Dockerfile
│   ├── Supfile
│   ├── example.dev.cfg
│   ├── example.go
│   ├── example.local.cfg
│   ├── example.prod.cfg
│   ├── example.stg.cfg
│   └── scripts
└── project3
    ├── Dockerfile
    ├── Supfile
    ├── example.dev.cfg
    ├── example.go
    ├── example.local.cfg
    ├── example.prod.cfg
    ├── example.stg.cfg
    └── scripts
```

**Comment by pkieltyka** [comment]
thats interesting.. would be nice to hear if there is more interest for this sort of thing, there are a few design I have in mind.

what would you see as the resulting command from the root? `sup project2 production deploy` ?

**Comment by eduardonunesp** [comment]
I was thinking in the following commands, from root:

`sup production deploy` to call deploy for all projects in the Supfile conf.
`sup production deploy --sub project2` to call deploy only for the project2.

The idea of Supfile for the root is something like:

```
env: # Environment variables for the commands
  NAME: rootproject

subs:
  project1:
    path: ./project1

  project2:
    path: ./project2

  project3:
    path: ./project3

commands: # Named set of commands to be run remotely in each sub project
  ping:
    desc: Print uname and current date/time.
    run: uname -a; date

  sub:
    task:
      - deploy

targets: # Aliases to run multiple commands at once
  deploy:
    - sub
```

**Comment by eduardonunesp** [comment]
Or

```
env: # Environment variables for the commands
  NAME: rootproject

subs:
  project1:
    path: ./project1

  project2:
    path: ./project2

  project3:
    path: ./project3

commands: # Named set of commands to be run remotely in each sub project
  ping:
    desc: Print uname and current date/time.
    run: uname -a; date

sub_targets:
  deploy:
    all: true
```

**Comment by VojtechVitek** [comment]
We could achieve this using `local` command -- see my comment at https://github.com/pressly/sup/issues/23#issuecomment-161676207

**Comment by stengaard** [comment]
I think an `include` option would be very useful in the sense that defining and re-using e.g. `networks` across projects would simplify multi-project deployments. I do agree that deploying sub-projects can be easily solved with `local` - but if these project need to go to the same host, then you need duplicate these networks across all projects.

**Comment by VojtechVitek** [comment]
@stengaard for reusing hosts across Supfiles, you'd probably use #9.

**Comment by stengaard** [comment]
Ok - I'll create a PR to get the ball rolling on that.

**Comment by VojtechVitek** [comment]
Closing in favor of #23. We can think of Supfile calling `sup -f ./another/Supfile` as Makefile calling `$(MAKE) -f ./another/Makefile`.

**Comment by eduardonunesp** [comment]
Agree, sorry to comment in a closed one, but the idea of an `include` command would be interesting.

**Comment by stengaard** [comment]
@eduardonunesp it would be useful, yes. But the semantics get quirky and the implementation I came up with was way less readable. 

Semantically: How is precedence handled? This has to be though out in case of both `networks`, `env` and `command` sections - with not necessarily the same answer. Do the values merge or override? What would the Supfile author expect? (I lean towards merging personally - but it's a bit harder to do.) 

Also if you can go arbitrarily deep down in to nested Supfiles it could eventually be a strain on the reader.

**Comment by VojtechVitek** [comment]
@stengaard @eduardonunesp what are you guys trying to solve with `include`? Is it that multiple Supfiles would share commands/targets? Can you provide some real-World examples?

**Comment by stengaard** [comment]
@VojtechVitek - I'm trying to come up with easy ways to re-use commands, networks and env across a lot of different projects. 

In case of web-apps using micro service architectures, each app created from the same app template. In this scenario you would only want to maintain the differences from the norm in each individual app. They would all share the same network and the same base set of commands (`package`, `unpack`, `start`, `stop`, ...). 


Consider `base.yaml` which is the base description that can then by overridden and added to in the Supfiles that include it:

```yaml
commands:
  check:
    run: test -z "$PRODUCT" && echo "Product not set" && exit 1
  pre-start:
    run: echo "-"
  start:
    run: monit start $PRODUCT
  post-start:
    run: echo "-"
  stop:
    run: monit stop $PRODUCT
... 
targets:
  deploy:
    - check
    - unpack
    - pre-start
    - start
    - post-start
...
```

Now in `app-a/Supfile` we would only need (using a few conventions and defaults):

```yaml
include:
  - ../base.yaml
env: 
  PRODUCT: app-a
```

And then `start`, `stop`, `pre-start`, `post-start`, ... could be overridden if needed. 

But

**Comment by anarcher** [comment]
Hi,

I really would like to use multiples Sups :-)

```
hosts:
    include: 
         - ./hosts-*.yml
commands:
    include: 
         - ./commands-base.yml
targets:
    include:
```

Sometimes, I make/use a host listing generation script. If sup can support `include` or something else, It should be great!

PS) Sup is very great tools for me. Specially If I manage multiple instances. Thanks for open-source.

**Comment by VojtechVitek** [comment]
@anarcher you can call `sup` from Supfile. This is what we do:

top-level Supfile:
```yml
commands:
  deploy-scheduler:
    desc: Deploy scheduler service
    local: sup $SUP_ENV -f ./services/scheduler/Supfile $SUP_NETWORK deploy
```

`sup production deploy-scheduler` triggers `sup -f ./services/scheduler/Supfile production deploy`
