### ISSUE TITLE
execute command in specific host

### ISSUE THREAD

**Issue by aminehmida** [pressly/sup#20]
Hi, I want to thank you for this nice tool. In fact, I was experimenting some deployment scenarios using sup and I have found a use case that is not covered in the example supfile and I don't know if it is currently even possible.

I want to tail-log from specific syslog server

```
tail-logs:
    desc: Tail syslog server
    run: tail -f /var/log/myapp.log
    host: syslog-server.myapp.com
```
Maybe we can add `host` field to force specific host. I know it is possible to add that host and add a tail-logs command but this command only make sense for the specific syslog host.

Thank you.
