### ISSUE TITLE
Detect the current network in /scripts/docker-run.sh

### ISSUE THREAD

**Issue by eduardonunesp** [pressly/sup#21]
I know that is possible to use variable ENV from network, like:

```
  dev:
    env:
      CURRENT_NETWORK: 'dev'
    hosts:
      - docker@192.168.99.100
```

But, would be cool if that environment variable was created automatically :)
