### ISSUE TITLE
Fabric?

### ISSUE THREAD

**Issue by brianreavis** [pressly/sup#22]
Just curious: in what ways does this differ from [fabric](http://www.fabfile.org/)? (apart from being written in Go)

**Comment by pkieltyka** [comment]
I'm not sure, I've tried or heard of fabric until a few days ago. Would be curious what people think too.

**Comment by eduardonunesp** [comment]
After rapid overview on Fabric documentation, I think that Sup looks like Fabric (just for an overview), I don't know Fabric deeply. Sup looks declarative, when you don't need to write some shell scripts.

**Comment by VojtechVitek** [comment]
@brianreavis I'm not sure about fabric functionality -- but what you can easily achieve using sup is for example interactive remote shell or interactive shell inside of remote running Docker containers. 

```yaml
  exec:
    desc: Exec into Docker container on all hosts
    stdin: true
    run: sudo docker exec -i $NAME bash

  shell:
    desc: Interactive shell on all hosts
    stdin: true
    run: /bin/sh
```

```
sup <network> exec
sup <network> shell
```

Also, I like the Supfile's declarative syntax. You don't need to know Python or Fabric API -- Supfile is just a simple YAML where you define bash commands (and thus any executables of your choice).
