### ISSUE TITLE
Run a local command 

### ISSUE THREAD

**Issue by eduardonunesp** [pressly/sup#23]
Could I run a local command as part of my set of commands ? For instance: I need to build a distribution package of my frontend in local machine and after that i need to upload to start the deploy.

Something like:

```
  prepare:
    desc: Prepare to upload
    run: npm run build
    local: true

  upload:
    desc: Upload this repository
    upload:
      - src: ./
        dst: /tmp/$IMAGE

targets:
  deploy:
    - prepare
    - upload
    .
    .
    .
```

So, after passing the `local : true` to my task, I'm sure that will be executed locally before the upload.

**Comment by VojtechVitek** [comment]
I was thinking of this use case just yesterday. Yea, I can add this functionality.

**Comment by eduardonunesp** [comment]
:+1:

**Comment by pkieltyka** [comment]
good idea. is `local: true` the best way to do it..? the most clear..?

**Comment by VojtechVitek** [comment]
Either that, or

```
 prepare:
    desc: Prepare to upload
    run_local: npm run build
```

**Comment by eduardonunesp** [comment]
Yeah, the option `run_local` looks good

**Comment by pkieltyka** [comment]
I kind of prefer how `local: true` looks

**Comment by eduardonunesp** [comment]
The `local: true` can be a pattern to run local or remote, the default is to run remote, but the local turn the command in a local command

**Comment by VojtechVitek** [comment]
On the other hand, what should happen on

```
 upload:
    desc: Upload
     - src: ./etc/config.cfg
       dst: /tmp/
    local: true
```

**Comment by eduardonunesp** [comment]
Good point, maybe that option can't apply to all commands

**Comment by eduardonunesp** [comment]
Done something here, it's very simple.

https://github.com/eduardonunesp/sup/commit/8b3bad7ca61a6f4948597970dc8dbcec28f3ff91

**Comment by eduardonunesp** [comment]
@VojtechVitek I know that you have a better idea :-)

**Comment by eduardonunesp** [comment]
https://github.com/pressly/sup/pull/28

**Comment by lexa-uw** [comment]
Hello all.

It is not good idea for using variable for running tasks "only on localhost".
In some cases code maybe prepeared on first host(localhos or diferent remote host) and deployed on second host(on remote or, maybe on localhost)

Will be better use next config:
```yuml
commands:
  nmpBuild:
    desc: Prepare to upload
    run: npm run build
    local: true

  upload:
    desc: Upload this repository
    upload:
      - src: ./
        dst: /tmp/$IMAGE

targets:
  prepare:
    - nmpBuild
  deploy:
    - upload
```
And run for build:
```bash
sup local prepare && sup remote deploy
```
Or
```bash
sup remote prepare && sup local deploy
```

**Comment by eduardonunesp** [comment]
The idea of `local : true` is an optional param, you don't need to use if you want, so the `Sup` will use the selected network as expected. Wherever the use of `local : true` is a sort of option for a lazy ones that want to do everything in one command like me :)

**Comment by VojtechVitek** [comment]
I like the `local` option mainly because you could run `sup` inside of `Supfile`. Thus you could do:

`sup production deploy`, which can internally run `sup builder build`

**Comment by lexa-uw** [comment]
I understand what do you want. :)
But this feature just syntax sugar. And it makes sup not really "Super simple deployment tool". I think.

**Comment by VojtechVitek** [comment]
@lexa-uw It's a good point and I don't disagree. But we need to solve the Supfile inside of Supfile somehow and I feel that running `sup` locally inside of Supfile would be the easiest way to achieve dependencies/imports. I completely agree on keeping sup as simple as possible. :)

**Comment by lexa-uw** [comment]
My sugestion replace ```local : true``` to ```network: $network$```
``` yaml
network:
  local:
    hosts:
      - localhost
  remote:
    hosts:
      - user@remote.host

commands:
  prepare:
    desc: Prepare to upload
    run: npm run build
    network: local

  upload:
    desc: Upload this repository
    upload:
      - src: ./
        dst: /tmp/$IMAGE

targets:
  deploy:
    - prepare
    - upload
```

```bash
sup remote deploy
```
Run ```prepare``` on ```local``` host and ```upload``` to ```remote``` host.

```bash
sup local deploy
```
Run all commands on ```local``` host.

**Comment by eduardonunesp** [comment]
Cool ! looks nice, that allows to combine others networks :+1:

**Comment by VojtechVitek** [comment]
I'm starting to like @lexa-uw's the idea of `network: $network$`. But I'd like to be even more specific and have `override_host` (or how do we call it) option instead. Example:

```yaml
commands:
    docker-build:
        description: Builds docker image on a builder host
        run: sudo docker build ....
        override_host: builder.example.com
    db-backup:
        description: Creates a database backup on DB host
        run: pg_dump ....
        override_host: db.example.com
    prepare:
        description: Prepares npm modules locally before upload
        run: npm instal ....
        override_host: localhost
```

What you guys think?

**Comment by pkieltyka** [comment]
I think this is pretty clever too, I like the use of "network" or "host".

I'd prefer to just go with "network" though, since it can reference the above network. I also think we should have a default network of "local" in each Supfile, unless its redefined in the network definitions list. This way, the "local" network is implied for all Supfile's.

That's my vote.

**Comment by VojtechVitek** [comment]
Guys, after a lot of thinking and doing some experiments, I changed my mind. I don't think that forcing network (or hosts) for a given command/target is such a good idea anymore.

Imho, the power of SUP is its simple CLI API -- `sup <network> <command>` -- and the network/host overriding would break it (or at least it would introduce really confusing behavior edge cases):

Given this Supfile:
```yaml
networks:
  local:
    hosts:
      - localhost
  builder:
    hosts:
      - builder.example.com
  production:
    hosts:
      - prod1.example.com
      - prod1.example.com

commands:
  prepare:
    network: local
    run: npm install ...
  build:
    network: builder
    run: docker build ...
  deploy:
    run: docker pull ... && docker stop ... && docker rm ... && docker run ...
```

What should really happen on following commands?
```bash
$ sup local deploy
# Should this really deploy on localhost, even thought "local" network
# was only meant to be used for "prepare" command?

$ sup builder deploy
# Same here. Should we deploy on builder hosts?

sup --only=prod1 production prepare
# Since we're forcing different <network> on the "prepare" command,
# what does `--only=prod1` option really do here?

# ...and the list goes on, even for such a simple example Supfile
```

Since we want to keep SUP the "super-simple deployment tool", I'd suggest stepping back to the original idea of "running local command" only.

And I don't want SUP to reimplement Ansible (or any other tool with hundreds of options). See Ansible's `local_action` vs. `delagate_to` delegation keywords at http://docs.ansible.com/ansible/playbooks_delegation.html.

---

Stepping back to the original idea of running local commands (compared to the snippet above):

./Supfile
```yaml
networks:
  production:
     hosts:
       - prod1.example.com

commands:
  prepare:
    run_locally: npm install ...
  build:
    run_locally: sup -f ./builder/Supfile $SUP_NETWORK build
  deploy:
    run: docker pull ... && docker stop ... && docker rm ... && docker run ...
```

./builder/Supfile
```yaml
networks:
  production:
     hosts:
       - builder.example.com

commands:
  build:
    run: docker build ...
```

As you can see, there are no such edge-cases, as mentioned above. And having multiple Supfiles referencing each other using `run_locally: sup -f ...` could solve the Supfile dependency/import feature, while keeping clean and independent Supfile "projects" (think of the `./builder/Supfile`, which can now be reused in multiple projects).
