### ISSUE TITLE
Add conditionals (skip_if_run, skip_if_script)

### ISSUE THREAD

**Issue by aelsabbahy** [pressly/sup#45]
Would be nice if a user can run a task conditionally, something along the lines of..

```yml
  config:
    desc: Upload/test config file if missing.
    upload:
      - src: ./example.$SUP_NETWORK.cfg
        dst: /tmp/
    skip_if_run: test -f /tmp/example.$SUP_NETWORK.cfg
```

**Comment by VojtechVitek** [comment]
Interesting indeed. This really applies to `upload` command only, since you can use the very same conditional as part of `run` or `local` commands. In that case, we might want to re-think the syntax of `upload` too..

On the other hand, `if` might apply to the whole command/target section.. But where is the conditional command run? Locally? Remotely? I guess remotely only.

My future syntax goal would be:
```yaml
  config:
    desc: Upload config file if missing.
    if: test ! -f /tmp/example.cfg
    local: echo 'Prepare example.$SUP_NETWORK.cfg locally'
    upload: ./example.$SUP_NETWORK.cfg /tmp/example.cfg
    run: echo 'Run some post-upload command..'
```
