### ISSUE TITLE
Allow argument on script

### ISSUE THREAD

**Issue by kureikain** [pressly/sup#48]
Can we considering allow extra argument on script, right now, if I write this:

```
  cleanup-release:
    desc: Cleanup old release
    stdin: true
    script: ./scripts/deploy/release -t cleanup
```

and run I got error:

```
2016/01/05 10:42:04 CreateTasks(): open ./scripts/deploy/release -t cleanup: no such file or directory
```

Granted, I can create separate script to avoid passing argument, but having argument in script is much more powerful. I can also sync the whole repo, and use `run` which allow argument but that seems dirty and require an extra definition task. 

I imagine it isn't that hard to add support for passing extra argument to script. Basically we can separate by space/tab to parse the script name and its argument, and if the script itself contains a space in its name or its path, we can require to put it in a quote. Or just not support having space in path/script name at all.
