### ISSUE TITLE
Shell commands .. like: sup production - ls -la

### ISSUE THREAD

**Issue by pkieltyka** [pressly/sup#6]

**Comment by VojtechVitek** [comment]
I just realized you could run `sup production exec <<< "echo sup"`. Would that be enough?

**Comment by eduardonunesp** [comment]
Looks good, but why the `sup production exec <<< "ls -la"` instead `sup production exec - ls -la`

**Comment by pkieltyka** [comment]
@eduardonunesp we get `<<<` for free which is one of the benefits

**Comment by eduardonunesp** [comment]
Cool :+1:

**Comment by VojtechVitek** [comment]
also you can use

`echo 'ls -la' | sup production shell`

**Comment by eduardonunesp** [comment]
Very cool, thanks for the tip

**Comment by VojtechVitek** [comment]
Another example

given
```yaml
commands:
   shell:
     desc: Interactive shell on all hosts
     stdin: true
     run: /bin/sh
```

you can pass in multiline input:
```bash
cat <<EOF | sup production shell
sudo apt-get update -y
date
uname -a
# any other commands here
EOF
```

I'll add this to README soon.
