### ISSUE TITLE
Better messages for upload errors

### ISSUE THREAD

**Issue by xiam** [pressly/sup#60]
Had something like this:

```
  config:
    upload:
      - src: ./etc/foo.$FOO.conf
        dst: /tmp/
```

The `./etc/foo.$FOO.conf` file didn't exist, `sup` tried to upload it anyway and that ended up on a remote `tar` error which was misleading.

Can `sup` alert and stop in case the `src` file does not exists?

**Comment by eduardonunesp** [comment]
It can be done by a local check before upload by `sup` or by another command which runs before the `upload`, for instance, you can set a command to check if `./etc/foo.$FOO.conf` exists, if file not exists you can abort by return something different of `0`.

```yml
 config:
  checkfile:
    run: test -e ./etc/foo.$FOO.conf
  upload:
    - src: ./etc/foo.$FOO.conf
      dst: /tmp/
```
