### ISSUE TITLE
Port forwarding

### ISSUE THREAD

**Issue by rubberydub** [pressly/sup#67]
Nice job!
Is port forwarding being currently/imminently developed? If not I will have a try.

**Comment by VojtechVitek** [comment]
Does this work for you?

```yaml
networks:
  dev:
    bastion: user@public.example.com:22
    hosts:
      - user@private.example.com:22
```
