### ISSUE TITLE
Multiple runs in a single command?

### ISSUE THREAD

**Issue by pyros2097** [pressly/sup#71]
I know this might deviate from your current plan but having this might really be good since I'm trying to port somethings from a makefile to supfile
```
commands:
  setup-go:
    desc: Setup tools used for go
    run: go get -u github.com/alecthomas/gometalinter
      - go get -u github.com/alecthomas/gometalinter
      - gometalinter --install --update
      - go get -u github.com/Masterminds/glide
      - go get -u github.com/pyros2097/go-embed
```
MaybeI could do it with multiple commands but it might get messy

**Comment by VojtechVitek** [comment]
Right now, you can simply do:

```yaml
commands:
  setup-go:
    desc: Setup tools used for go
    run: >
      go get -u github.com/alecthomas/gometalinter && \
        go get -u github.com/alecthomas/gometalinter && \
        gometalinter --install --update && \
        go get -u github.com/Masterminds/glide && \
        go get -u github.com/pyros2097/go-embed
```

----------

But I'm actually thinking of allowing multiple `run`s like this:
```yaml
commands:
  setup-go:
    desc: Setup tools used for go
    run: go get -u github.com/alecthomas/gometalinter
    run: go get -u github.com/alecthomas/gometalinter
    run: gometalinter --install --update
    run: go get -u github.com/Masterminds/glide
    run: go get -u github.com/pyros2097/go-embed
```

It's not on my TODO list, though. I can prioritize if there's a bigger demand for this feature.

**Comment by pkieltyka** [comment]
I think run: > is just fine IMO.. Just needs to be documented as an example

**Comment by VojtechVitek** [comment]
btw: You can also
```yaml
setup-go:
  run: go get -u github.com/alecthomas/gometalinter; gometalinter --install --update
```

**Comment by eduardonunesp** [comment]
I like the idea of run, run, run

```YAML
commands:
  setup-go:
    desc: Setup tools used for go
    run: go get -u github.com/alecthomas/gometalinter
    run: go get -u github.com/alecthomas/gometalinter
    run: gometalinter --install --update
    run: go get -u github.com/Masterminds/glide
    run: go get -u github.com/pyros2097/go-embed
```

**Comment by pyros2097** [comment]
I guess the second way is better and I think thats how they do it in ansible also. >_

**Comment by pkieltyka** [comment]
Majority consensus rules :)

**Comment by VojtechVitek** [comment]
It's not only about the syntax sugar, multiple runs might have interesting side effects, when combining with other commands too.

```
commands:
  build:
    local: npm install
    upload:
       src: ./npm_modules
       dest: $WORKDIR/
    run: cd $WORKDIR && docker build -t image:$VERSION .
    run: docker push image:$VERSION
    local: curl #....webhook for Slack
```

The only problem is ... what about `run` flags (ie. `once: true`, `serial: 2`)? Do they apply to all `run` commands? Do they apply to the previously declared `run` command only? Same thing to consider for `onerror` roll back commands (#42).
