### ISSUE TITLE
Group commands based on networks?

### ISSUE THREAD

**Issue by pyros2097** [pressly/sup#76]
Just as we have different hosts, can't we have commands that run on different host. Like I don't want to run the build command on my production host but would like to have it only in development. In ansible we generally use roles for this I think.
```yaml
networks:
  dev:
    hosts:
      - localhost
  prod:
    hosts:
      - api1.example.com
      - api2.example.com

commands:
  dev:
    build:
      desc: Build the go binary
      run: go build . -o project
  prod:
    upload:
      desc: Upload the go binary
      upload: ./project
```

**Comment by eduardonunesp** [comment]
Sup don't have these rules, instead it let you free to leverage the `sh` shell or `bash`. I have created a basic solution. Actually I think you have two options.

First:
```YAML
version: 0.3

networks:
  dev:
    hosts:
      - dev.example.com

  prod:
    hosts:
      - prod.example.com

commands:
  build:
    run: |
      if [[ $SUP_NETWORK != dev ]]; then exit 0; fi
      echo "BUILD!"

  something:
    run: echo "FOOBAR"

targets:
  deploy:
    - build
    - something
```

Second: 
```YAML
version: 0.3

networks:
  dev:
    hosts:
      - dev.example.com

  prod:
    hosts:
      - prod.example.com

commands:
  build:
    run: echo "BUILD!"

  something:
    run: echo "FOOBAR"

targets:
  run_dev:
    - build
    - something

  run_prod:
    - something
```

**Comment by VojtechVitek** [comment]
We considered having this functionality, since this is quite common use case - but we wanted to keep SUP as simple as possible.

That's why we introduced `$SUP_NETWORK` env var instead so you can nest sup commands like this:

Supfile:
```yaml
networks:
  production:
     hosts:
        - api1.example.com
        - api2.example.com
        - api3.example.com

commands:
  build:
    local: sup -f ./Supfile.builder $SUP_NETWORK build
```

Supfile.builder:
```yaml
networks:
  production:
     hosts:
        - builder.example.com

commands:
  build:
    run: docker build -t image . && docker push image
```

`sup production build` will build docker image only on builder.example.com.

@pyros2097 @eduardonunesp Does this make sense? I didn't do a good job documenting this feature, let me fix that.
