### ISSUE TITLE
Dynamic hosts list from command or http endpoint

### ISSUE THREAD

**Issue by pkieltyka** [pressly/sup#9]
ie..

```
# Some Supfile
---

env:
  NAME: x

networks:
  production:
    hosts: http://discovery.etcd.io/asdfasdf/hosts

commands:
  .....
```

the hosts expects hosts on newlines, and will use that list for the present time. This is useful to automated environments. We could also allow `hosts: $ command`
