### ISSUE TITLE
Command options as Packages

### ISSUE THREAD

**Issue by chonthu** [pressly/sup#92]
run, local, and many more user contributed actions as "packages". More Ansible style "tasks" maybe a "yum" package etc. 

example:

```
# Supfile

commands:
    install:
        desc:Install apache server
        yum: name=apache state=running
```

thoughts?

**Comment by VojtechVitek** [comment]
We're not trying to reimplement Ansible. Sup is just a simple SSH multiplexer that runs commands remotely.

You can run scripts, though:
```yaml
# Supfile

commands:
    install:
        desc: Install apache server
        script: apache-running.sh
```
