### ISSUE TITLE
target call target, display "Unknown command/target"

### ISSUE THREAD

**Issue by andares** [pressly/sup#98]
```
$ sup -f elk.yml local install
Targets:   
- java     start date
- install  java add-key
           
Commands:  
- start    Print some env vars
- date     Print OS name and current date/time
- add-key  add apt key

Unknown command/target: java
```

how does it work?

supfile content like:

```
commands:
    start:
        desc: Print some env vars
        run: echo \>\>\> start run for $SUP_NETWORK
    date:
        desc: Print OS name and current date/time
        run: uname -a; date
    add-key:
        desc: add apt key
        run: wget -qO - https://packages.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -

targets:
    java:
        - start
        - date
    install:
        - java
        - add-key
```
